<a href="https://colab.research.google.com/github/tonpiplaifa/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np

Numpy array

In [31]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [32]:
np2 = np.array([[1,2], [3,5], [2,0], [4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [6]:
np2.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [7]:
np2[0,:]

array([1, 2])

## HW6 สร้าง Distance metrix (Euclidean) ของ np2 
โดยสร้าง function สำหรับคำนวณ Euclidean Distance

In [15]:
import math

In [51]:
def Euclidean(data1,data2) :
    distX = math.sqrt(pow(abs(data1[0]-data2[0]),2))
    distY = math.sqrt(pow(abs(data1[1]-data2[1]),2))
    return distX+distY

In [52]:
dist_math = np.zeros((4,4))
dist_math

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
for i in range(4):
  for j in range(4):
    dist_math [i,j] = Euclidean(np2[i,:],np2[j,:])

dist_math 

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [54]:
Euclidean(np2[0,:],np2[1,:])

5.0

### ตัวอย่างการคำนวณ Distance metrix ที่ระยะทางเป็น Manhattan

In [8]:
import math

In [9]:
def Manhattan(data1,data2) :
    distX = abs(data1[0] - data2[0])
    distY = abs(data1[1] - data2[1])
    return distX+distY

In [10]:
Manhattan(np2[0,:],np2[1,:])

5

In [11]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
dist_mat = np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
for i in range(4):
  for j in range(4):
    dist_mat [i,j] = Manhattan(np2[i,:],np2[j,:])

dist_mat 

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])